### ISSUE TITLE
Bug spam click

### ISSUE THREAD

**Issue by Myystigri** [radial-color-picker/react-color-picker#1]
If you spam the select button it get stuck in a weird state (sometime the cursor to select is displayed but not the wheel or the opposite might happen too) until you reload the page. 

It can be reproduced here https://codepen.io/rkunev/pen/mjKoyK/

**Comment by rkunev** [comment]
I think the issue was reproducible in the Vue component as well, but I fixed it there. Stay tuned, I already started some time ago porting the functionalities (and bugfixes).

**Comment by Myystigri** [comment]
alright, thanks !

**Comment by rkunev** [comment]
Fix available in [v2.0.0](https://www.npmjs.com/package/@radial-color-picker/react-color-picker)
