### ISSUE TITLE
dependency conflict when installing this package in a React 18 app as this depends on React 16 o React 17

### ISSUE THREAD

**Issue by jandres234** [radial-color-picker/react-color-picker#4]

**Comment by rkunev** [comment]
Peer dependencies have been bumped to React 17 or React 18 in `v4.0.1` (along with other breaking changes). Migration guide is [here](https://github.com/radial-color-picker/react-color-picker#migration), but most likely you'll need to update just the path of the component stylesheet `react-color-picker.min.css` to `style.css`.
